### ISSUE TITLE
Help wanted - more examples

### ISSUE THREAD

**Issue by alexellis** [alexellis/actions-batch#1]
Take a look at some of the examples:

https://github.com/alexellis/actions-batch/tree/master/examples

I'd like submissions for things that can run in the foreground or run until completion.

Some ideas: headless Chrome / puppeteer / Postgresql or similar queries via CLI, running e2e tests - perhaps the ones from the openfaas/faas-netes repo? Testing out a Helm chart by installing it via arkade? Running hey against your own HTTP server?

**Comment by StevenACoffman** [comment]
So is there any way to have the created job use [workload identity](https://github.com/google-github-actions/auth#setup)? 
I need to add a step something like this to the github action:
```
    - name: 'Authenticate to Google Cloud'
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/XXXX/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-provider'
        service_account: 'XXXX@XXXX.iam.gserviceaccount.com'
```


Here's a more complete example of one of my current workflow file:
```
name: image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# only on merge to master unless debugging this workflow
#  pull_request:
#    branches:
#      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  ko_publish:
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, linux, x64]
    timeout-minutes: 30
    # Adds "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Clone Repository (Latest)
      uses: actions/checkout@v4
      if: github.event.inputs.git-ref == ''
    - name: Clone Repository (Custom Ref)
      uses: actions/checkout@v4
      if: github.event.inputs.git-ref != ''
      with:
        ref: ${{ github.event.inputs.git-ref }}
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.x
        cache-dependency-path: "**/*.sum"
    # Install gcloud, do not specify authentication.
    - name: Setup Gcloud
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: XXXXX
        # export_default_credentials: true
        # Old bad way without workload identity federation:
        # service_account_key: ${{ secrets.GCP_GCR_SA_KEY }}
        # service_account_email: ${{ secrets.GCP_GCR_SA_EMAIL }}
    # Configure Workload Identity Federation via a credentials file.
    - name: 'Authenticate to Google Cloud'
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/XXXXX/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-provider'
        service_account: 'XXXX@XXXX.iam.gserviceaccount.com'
        #  token_format: 'access_token'
    # Authenticate using the created credentials file.
    #
    # WARNING: The --cred-file flag is in preview and is subject to change.
    # Configure Workload Identity Federation via a credentials file.
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        echo starting the gcloud thing
        gcloud auth login --brief --force --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        echo "checking if that worked by listing active sessions"
        gcloud auth list
        echo "Configuring docker to use the gcloud command-line tool as a credential helper"
        gcloud auth configure-docker -q us-central1-docker.pkg.dev
    - id: 'build-image'
      name: 'build-image'
      run: |-
        # Build ko from HEAD, set up auth to ghcr.io, build and push an image
        # tagged with the SHA.
          echo "GOBIN=${GOBIN}"
          echo "PATH=${PATH}"
          go install github.com/google/ko@latest
          # Loop through the top level build directories, and build independently.
          for d in */; do
            config="${d}.ko.yaml"
            if [[ ! -f "${config}" ]]; then
              echo "${d} skipping: ${config} not found."
              continue
            fi
            ## This will run ko in each directory each 
            echo "Building $d ... "
            cd "${d}"
            ./ko.sh
            cd ..
          done
```


I happen to have a GKE cluster, so I do most of my stuff in Go with [your run-job](https://github.com/alexellis/run-job) and [ko](https://ko.build/reference/ko/), and I just wondered if I could skip the cluster and just execute in github, but I'd need workload identity to talk to other GCP services.

It is completely fine to ignore this, but if workload identity was already easy, it would expand actions-batch potential use cases for me.

**Comment by alexellis** [comment]
Thanks for using run-job, that's the first time I've heard from yourself.

How do you use run-job at the moment?

Re: workflow identity.

Do you just need the below inject in the top of the workflow template file?

```
    - name: 'Authenticate to Google Cloud'
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/XXXX/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-provider'
        service_account: 'XXXX@XXXX.iam.gserviceaccount.com'
```

You could try editing this file, and just insert it: https://github.com/alexellis/actions-batch/blob/master/templates/workflow.yaml

Then make a new build of the project.

Let me know if that resolves it for you?
